### ISSUE TITLE
handle rate limiting

### ISSUE THREAD

**Issue by zkoppert** [zkoppert/innersource-crawler#6]
https://github.com/zkoppert/innersource-crawler/blob/3730f4b41ffb2526b6c6a11341f2c79e7461c2a7/crawler.py#L32-L32

**Comment by spier** [comment]
I noticed that in the current implementation you are [fetching all repos](https://github.com/zkoppert/innersource-crawler/blob/main/crawler.py#L21) accessible via the GH Access Token, rather than searching for repos with a given topic only. 

Searching by topic would likely bring down the amount of API calls you need quite a bit as well.

Did you choose the current implementation because you don't want to limit this to a single GitHub org?

**Comment by zkoppert** [comment]
@spier Good question! I did it this way because I couldn't figure out how to only fetch repos with a given topic. That would be much more efficient! Any ideas on how to do that?

**Comment by spier** [comment]
At least when searching for repos on github.com, you can [search like this](https://github.com/search?q=org%3Ameltwater+is%3Apublic+topic%3Adrone):
`org:meltwater is:public topic:drone`

That would return all public repos from my org `meltwater` containing the topic `drone`.

I see that in your code you use this right now:
`all_repos = gh.repositories()`

Instead it might be something similar to this, of course replacing things accordingly based on your `.env`:
`all_repos = gh.search_repositories("org:meltwater is:public topic:drone")`

_Note:_ I didn't try this out yet.
